services:
  mongo1:
    image: mongo:8.0-noble
    container_name: mongo1
    volumes:
      - mongo1-data:/data/db
    ports:
      - "27017:27017"
    command: ["mongod", "--replSet", "pmpReplicaSetDev", "--bind_ip_all"]
    networks:
      - defaultNetwork
      - mongoCluster

  mongo-init:
    image: mongo:8.0-noble
    depends_on:
      - mongo1
    entrypoint: >
      bash -c "
      sleep 5;
      mongosh --host mongo1 --eval '
        rs.initiate({
          _id: \"pmpReplicaSetDev\",
          members: [
            { _id: 0, host: \"mongo1\" },
          ]
        })
      '"
    networks:
      - mongoCluster

networks:
  defaultNetwork:
    driver: bridge
  mongoCluster:

volumes:
  mongo1-data: