const DEPARTMENTS = [
  "College of Engineering",
  "College of Nursing",
  "Kindergarten",
  "Elementary School",
  "Junior High School",
  "Senior High School",
  "College of Agriculture Resources & Environmental Sciences",
  "College of Arts & Sciences",
  "College of Business and Accountancy",
  "Computer Studies",
  "College of Education",
  "College of Hospitality Management",
  "College of Pharmacy",
  "College of Medical Laboratory",
  "College of Medicine",
  "College of Graduate Studies",
  "College of Theology",
  "College of Law",
  "Office of the President",
  "Office of the Vice President for Administration",
  "Office of the Vice President of Academic Affairs",
  "Office of the Vice President of Student Affairs",
  "Registrar's Office",
  "Library",
  "University Computer Service Center",
  "Student Development Programs",
  "Buildings Upkeep and Maintenance",
  "Campus Traffic",
  "Security and Safety",
  "Electrical & Mechanical Systems",
  "Facilities Maintenance and Services",
  "Grounds Upkeep and Maintenance",
  "Occupational Safety and Health Officer",
  "Pollution Control",
  "Swimming Pool",
];

export default DEPARTMENTS;
